services:
  mc:
    image: energypatrikhu/pterodactyl-minecraft-server
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    volumes:
      - data:/home/container
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
