#!/bin/bash

# shellcheck source=start-utils
. "$(dirname "$0")/start-utils"

# The Dockerfile ENVs take precedence here, but defaulting for testing consistency
: "${UID:=988}"
: "${GID:=988}"
: "${SKIP_CHOWN_DATA:=false}"

umask "${UMASK:=0002}"

# Remove from previous run and do this as elevated user since file used to be created before demoting
rm -f "$HOME/.rcon-cli.env"

if ! isTrue "${SKIP_SUDO:-false}" && [ "$(id -u)" = 0 ]; then
  runAsUser=container
  runAsGroup=container

  if [[ -v UID ]]; then
    if [[ $UID != 0 ]]; then
      if [[ $UID != $(id -u container) ]]; then
        log "Changing uid of container to $UID"
        usermod -u $UID container
      fi
    else
      runAsUser=root
    fi
  fi

  if [[ -v GID ]]; then
    if [[ $GID != 0 ]]; then
      if [[ $GID != $(id -g container) ]]; then
        log "Changing gid of container to $GID"
        groupmod -o -g "$GID" container
      fi
    else
      runAsGroup=root
    fi
  fi

  if isFalse "${SKIP_CHOWN_DATA}" && [[ $(stat -c "%u" /home/container) != "$UID" ]]; then
    log "Changing ownership of /home/container to $UID ..."
    chown -R ${runAsUser}:${runAsGroup} /home/container
  fi

  if [[ ${SKIP_NSSWITCH_CONF^^} != TRUE ]]; then
    echo 'hosts: files dns' > /etc/nsswitch.conf
  fi

  exec gosu ${runAsUser}:${runAsGroup} "$(dirname "$0")/start-configuration" "$@"
else
  exec "$(dirname "$0")/start-configuration" "$@"
fi
